# Generated by Django 5.2.13 on 2026-06-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='recipe_description',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='recipe_image',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='recipe_name',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='receipe_description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='receipe_image',
            field=models.ImageField(default=None, upload_to='C:\\Users\\shubh\\OneDrive\\Desktop\\django practice\\kitchen\\receipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='receipe_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
